### ISSUE TITLE
Create method generate the following error.

### ISSUE THREAD

**Issue by raphdg** [SeyZ/baboon#50]
```
~/projects/internal/baboon (master *) $ python bin/baboon create techta --path /tmp
Creation in progress...
Traceback (most recent call last):
  File "bin/baboon", line 7, in <module>
    Main()
  File "/home/raph/projects/internal/baboon/baboon/main.py", line 30, in __init__
    getattr(commands, self.which)()
  File "/home/raph/projects/internal/baboon/baboon/commands/commands.py", line 84, in create
    with AdminTransport(logger_enabled=False) as transport:
  File "/home/raph/projects/internal/baboon/baboon/transport.py", line 53, in __enter__
    self.open()
  File "/home/raph/projects/internal/baboon/baboon/transport.py", line 69, in open
    self.process(block=block)
  File "/home/raph/projects/external/SleekXMPP/sleekxmpp/basexmpp.py", line 191, in process
    self.plugin[name].post_init()
  File "/home/raph/projects/external/SleekXMPP/sleekxmpp/plugins/xep_0004/dataforms.py", line 50, in post_init
    self.xmpp.plugin['xep_0030'].add_feature('jabber:x:data')
KeyError: 'xep_0030'
```

**Comment by SeyZ** [comment]
Fixed. It was a problem in your virtualenv.
